/** @type {import('tailwindcss').Config} */
// PRESCOPE — SPECIMEN. Paper and ink.
// Keep in sync with lib/specimen-tokens.ts and global.css.
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        paperSheet: "#f5f2eb",
        paperMount: "#fcfbf7",
        paperDeep: "#eae5d8",
        paperPlate: "#e3ddce",
        inkFull: "#1b1a17",
        inkSoft: "#56524a",
        inkFaint: "#8c8678",
        inkGhost: "#b4ae9f",
        rule: "#d8d2c4",
        ruleStrong: "#bdb5a2",
        tag: "#a4341f",
        tagWash: "#f3e4e0",
        sage: "#5f6b4c",
        sageWash: "#e7eade",
        ochre: "#9a6b28",
        ochreWash: "#f4ebda",
        primaryBlue: "#a4341f",
        deepNavy: "#1b1a17",
        skyBlue: "#a4341f",
        iceBlue: "#f5f2eb",
        deepTeal: "#a4341f",
        midTeal: "#a4341f",
        lightTeal: "#f3e4e0",
        teal: "#a4341f",
        sageLight: "#e7eade",
        coral: "#a4341f",
        coralLight: "#f3e4e0",
        amber: "#9a6b28",
        amberLight: "#f4ebda",
        cream: "#f5f2eb",
        white: "#fcfbf7",
        slate: "#56524a",
        mist: "#8c8678",
        border: "#d8d2c4",
        charcoal: "#1b1a17",
        orangeDark: "#a4341f",
        orangeBright: "#a4341f",
        orangeLight: "#a4341f",
        softWhite: "#f5f2eb",
        pureWhite: "#fcfbf7",
        orangeTint: "#f3e4e0",
        orangeTintDeep: "#eae5d8",
        darkText: "#1b1a17",
        bodyText: "#56524a",
        mutedText: "#8c8678",
        placeholderText: "#b4ae9f",
        borderLight: "#d8d2c4",
        borderMedium: "#bdb5a2",
        successGreen: "#5f6b4c",
        warningAmber: "#9a6b28",
        dangerRed: "#a4341f",
        riskLow: "#5f6b4c",
        riskModerate: "#9a6b28",
        riskHigh: "#a4341f",
      },
    },
  },
  plugins: [],
};
